### ISSUE TITLE
modify README.md

### ISSUE THREAD

**Issue by teddy309** [namdori61/BERT-Korean-Classification#1]
'README.md'에서 아래와 같은 수정사항이 하나 발견되어 이슈 남깁니다.
![image](https://user-images.githubusercontent.com/22393059/113878705-d1a50780-97f4-11eb-8653-40ec72542f7d.png)

위의 부분 중 'train.py'를 실행하는 커멘드 예시 'python train.py ....'에서 --lr 변수 정의하는 부분이 다음과 같이 중복된 것 같습니다.
--lr LR 
--lr LEARNING_RATE

**Comment by namdori61** [comment]
@teddy309 
그러네요, 피드백 주셔서 감사합니다 :)
수정하였습니다.
